### ISSUE TITLE
导入密钥错误

### ISSUE THREAD

**Issue by xuelingkang** [manjarocn/repo#1]
执行命令：`sudo pacman-key --recv-keys 974B3711CFB9BF2D`
报错：
```
gpg: keyserver receive failed: No name
==> ERROR: Remote key not fetched correctly from keyserver.
```
这个问题应该怎么解决，另外我想问一下，manjarocn有没有国内镜像

**Comment by jat001** [comment]
1. [change the keyserver](https://www.reddit.com/r/archlinux/comments/o5rcs6/psa_you_need_to_update_your_keyserver/)
2. no mirror on mainland china yet

**Comment by xuelingkang** [comment]
Thanks for your help!
`keyserver hkps://keyserver.ubuntu.com` works for me.
